SET SERVEROUTPUT ON;

--CHANGE PASSWORD TEST;
DECLARE
PIS_PHONE       USER_INFO.PHONE_NUMBER%TYPE     := '5552237945';
PIS_TC_NUMBER   USER_INFO.TC_NO%TYPE            := '22222222222';
PIS_NEW_PASS    USER_INFO.PASS_WORD%TYPE        := 'Tolga123';
CHECKER NUMBER;
BEGIN
    CHANGE_PASSWORD(PIS_PHONE, PIS_TC_NUMBER, PIS_NEW_PASS, CHECKER);
END;
/

--CHECK USER TEST;
DECLARE
CHECKER NUMBER;
PIS_PHONE   USER_INFO.PHONE_NUMBER%TYPE   :='5514424516';
PIS_PASS    USER_INFO.PASS_WORD%TYPE      :='Yunus123456';
BEGIN
    CHECK_USER(PIS_PHONE, PIS_PASS, CHECKER);
END;
/

--CREATE USER TEST;
DECLARE
PIS_F_NAME       USER_INFO.FIRST_NAME%TYPE      :='YUNUS';
PIS_L_NAME       USER_INFO.LAST_NAME%TYPE       :='DENEME5'; 
PIS_P_NUMBER     USER_INFO.PHONE_NUMBER%TYPE    :='5551119451';
PIS_E_MAIL       USER_INFO.EMAIL%TYPE           :='mail@mail3.com'; 
PIS_P_WORD       USER_INFO.PASS_WORD%TYPE       :='Mammamia077';
PIS_B_DAY        USER_INFO.BIRTHDATE%TYPE       :='05-01-1990';
PIS_TC_NUMBER    USER_INFO.TC_NO%TYPE           :='54544511188';
CHECKER         NUMBER;
BEGIN
    CREATE_USER(PIS_F_NAME, PIS_L_NAME, PIS_P_NUMBER, PIS_E_MAIL, PIS_P_WORD, PIS_B_DAY, PIS_TC_NUMBER, CHECKER);
END;
/

--GET BALANCES TEST;
DECLARE
PIS_PHONE   USER_PKG_BALANCE.PHONE_NUMBER%TYPE    := '5551119451';
REMAIN_GB   USER_PKG_BALANCE.DATA_GB_BAL%TYPE;
REMAIN_MIN  USER_PKG_BALANCE.VOICE_BAL%TYPE;
REMAIN_SMS  USER_PKG_BALANCE.SMS_BAL%TYPE;
BEGIN
    GET_BALANCES(PIS_PHONE, REMAIN_GB, REMAIN_MIN, REMAIN_SMS);
END;

